### ISSUE TITLE
Help created a directed/tree layout

### ISSUE THREAD

**Issue by tylerecouture** [cytoscape/cytoscape.js-cola#10]
Hi! I was using a dagre layout but it was suggested I try cola as it supports compound nodes.

Here is what I can "fake" using dagre:
http://jsbin.com/cipoqes/edit?html,output

But I don't seem to be able to replicate it using cola with flow:
http://jsbin.com/gomido/edit?html,output

I've looked at the downward flow example here:http://marvl.infotech.monash.edu/webcola/examples/downwardedges.html
but can't figure out the parameters I need to use to get a similar result.

Any suggestions?

Thanks for any help you can provide!

**Comment by EyMaddis** [comment]
I played around a bit and noticed that it basically looks pretty good, but it seems to do not have enough time, especially since the edges are overlapping.
In order to mitigate this you can take a look at the three properties which set initial layouting, taken from the README.md:

```js
// iterations of cola algorithm; uses default values on undefined
  unconstrIter: undefined, // unconstrained initial layout iterations
  userConstIter: undefined, // initial layout iterations with user-specified constraints
  allConstIter: undefined, // initial layout iterations with all constraints including non-overlap

```
`unconstrained` here means that these are the layouting steps that are used to place the nodes initially and spread them out. ´user constraints` refer to special constraints that you can choose, I would guess that this also includes the flow layout.
So setting these will give cola more time to figure stuff out.

These properties are also the arguments for the `start()` method from cola, so looking at the source code of the [downward edges example](http://marvl.infotech.monash.edu/webcola/examples/downwardedges.html) you can see that they use values of 10 and 20 in line 54.

I added the properties to your [jsbin example](http://jsbin.com/gofilovewe/edit?html,output) which looks like this:

![image](https://cloud.githubusercontent.com/assets/1409100/18123341/b7adaf08-6f6d-11e6-8aed-9e8eaeb9a503.png)
