### ISSUE TITLE
cannot interact when infinite mode is on

### ISSUE THREAD

**Issue by EyMaddis** [cytoscape/cytoscape.js-cola#13]
This gif pretty much sums it up:
![cola-infinite](https://cloud.githubusercontent.com/assets/1409100/18246913/3c7f31a2-736f-11e6-9c88-3b0679bbe95a.gif)

using the following layout options:

``` js
            ungrabifyWhileSimulating: false, // true of false does not matter for this issue
            infinite: true

            refresh: 4,
            avoidOverlap: true,
            edgeLength: 250,
            unconstrIter: 100,
            userConstIter: 0,
            allConstIter: 10
```

Not only is the layout (node positions) blocked, but also the whole viewport (scale/position). It just jumps back to the position determined by cola.

**Comment by maxkfranz** [comment]
If `fit: true`, it's going to `cy.fit()` each update.

If `ungrabifyWhileSimulating: true`, you can't grab.  If there's already not, there should probably be a `node.grabbed()` check before allowing Cola to set position.

**Comment by EyMaddis** [comment]
I actually think it is related to https://github.com/cytoscape/cytoscape.js-cola/issues/14.
The layout has completely separate elements it works on which are transformed from the original cytoscape elements. 
When a user grabs a node, cytoscape updates the node position, but that is never mirrored to the objects the layout works with. Therefore the next tick of the layouting will reset the positions.

Right now it is just data from cytoscape to layout once, then arbitrary updates the positions which cytoscape will use happily.

**Comment by maxkfranz** [comment]
It looks like the extension already handles grabbing and updating internal cola positions on drag: https://github.com/cytoscape/cytoscape.js-cola/blob/master/cytoscape-cola.js#L281

The `scrCola` object is the object that Cola owns.

Maybe the version of Cola you're using changed its adaptor interface again?

**Comment by EyMaddis** [comment]
Also appears in this JSBin: http://jsbin.com/gutipokojo/1/edit?html,js,output
Infinite is not active, but the same issue appears whenever while the layout is still animating (mouse interactions need to be fast ;) )

**Comment by maxkfranz** [comment]
See the above commit for info re. change list and code diff.  This seems to work more like how Cola does internally (undocumented).  It works for noncompound graphs, and it should probably work for compounds.  I didn't have time to test with compound ones, though.

**Comment by EyMaddis** [comment]
Works great.
A very minor thing is that dragging compound nodes will pause the layouting until mouseup. After the dragging stopped, the layout will adjust for the new position. This only happens for compound graphs, regular graphs will also animate while the dragging is still in progress.

I would say that it is perfectly usable :) 

Great work, thanks!

I added infinite mode to the jsbin: http://jsbin.com/jodogu/1/edit?html,js,output

**Comment by maxkfranz** [comment]
It definitely works better for noncompound graphs than compound ones.

Here's the official Cola demo: http://marvl.infotech.monash.edu/webcola/examples/smallgroups.html

It looks like they call [`dragStart()`](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L783), [`drag`](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L829) and `resume()` , and then close with [`dragEnd()`](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/layout.ts#L850): https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/d3adaptor.ts#L28

We're following the same flow, but I suppose we never directly drag parents.  Maybe we shouldn't be sending back `px` and `py` for compound parents?  Otherwise, I'm not sure what would be different.  Maybe the Cola author, Tim, would know more.
