### ISSUE TITLE
avoidOverlap still causes overlap with compound nodes

### ISSUE THREAD

**Issue by felixfbecker** [cytoscape/cytoscape.js-cola#18]
Take this example with D3: http://marvl.infotech.monash.edu/webcola/examples/smallworldwithgroups.html

Dragging nodes inside a group will never cause a node to overlap with a foreign group or two groups to overlap.
cytoscape-cola positions nodes over other compound nodes:

![image](https://cloud.githubusercontent.com/assets/10532611/26025314/060c318e-37e5-11e7-9325-a86163b91e30.png)

**Comment by maxkfranz** [comment]
If you want to use Cola, then you can only use features that Cola has designed around.  Cytoscape.js has more features than what Cola takes into account (like padding and label bounding boxes).

**Comment by felixfbecker** [comment]
why does it work with D3 then?

**Comment by maxkfranz** [comment]
Because as I said, the D3/Cola demo doesn't support things like compound bounding boxes that update based on child labels or compounds with paddings.  Cola doesn't support things like that.  If you want to use Cola, you need to simplify your graph style or use a more sophisticated layout like CoSE-Bilkent.
