### ISSUE TITLE
Is it possible to specify that layout should be as zoomed in as possible when updating?

### ISSUE THREAD

**Issue by baieric** [cytoscape/cytoscape.js-cola#50]
I have a canvas that is typically the entire screen (so 16:9 ratio typically). The user can add nodes, and I like how cola animates this node being added in a way that the old layout is somewhat preserved usually, for visual continuity. I have either one or two disconnected graphs at once.

When nodes get added, I set the initial position to be the average of the coordinates of all its connections (there is guaranteed at least one connection). the layout zooms out as needed so that as much of the graph can be seen in the canvas, which is great. The thing is, the canvas has a lot of empty, unused space when this happens. Often, adding a node will add the node above/below a connected node, and there's a lot of horizontal space wasted. For example, cola will have one disconnected graph above another, when they could fit the space a lot better if they were horizontally side by side. My goal is for the graph to be as zoomed in as possible while fitting the entire graph in the canvas, but this sub-optimal layout causes the graph to be quite zoomed out.

Is this something cola could consider when running the layout? Would this be easy for me to configure somewhere?

Thanks so much!

**Comment by janhartmann** [comment]
This is also something I am really needing. 

Making Cola use up as much space as possible while respecting the bounding box. Tried setting `fit: false` and hoping it would stay within the bounding box, but it did not work. Any suggestions are welcome.

**Comment by maxkfranz** [comment]
You could ask the author of the algorithm, Tim, at https://github.com/tgdwyer/WebCola.  This repo is just a wrapper so that the Cola algorithm works with Cytoscape.

Generally, force-directed layouts don't use all the screen space.  They're constrained by the forces and generate an equilibrium state -- which may or may not use all the screen space.  The only FD layout that guarantees all the screen space is used is Spread (by stretching things out), but that creates a different aesthetic.  If you have disconnected components, FCOSE does a good job of packing them to use up most of the screen.  For Cola, you should ask Tim.

**Comment by maxkfranz** [comment]
See also https://blog.js.cytoscape.org/2020/05/11/layouts/

**Comment by baieric** [comment]
> See also https://blog.js.cytoscape.org/2020/05/11/layouts/

Thanks @maxkfranz, I've tried these and cola is still the best for my use case. Is there no config to simply make cola prefer adding nodes to the left and right of its neighbors? It seems to tend to add nodes top and bottom first.

**Comment by janhartmann** [comment]
Cola also renders my graph the best, however we recently had to switch to d3-force for this issue alone. 

I asked a question on Stack Overflow with this issue and @hasanbalci  was very nice to reply on how to achieve this with Cola.

See: https://stackoverflow.com/questions/63841671/y-axis-force-with-cola-js-and-cytoscape

However, it was hard to implement in a very changing dataset in my use case, so we went with d3-force where it is possible to apply force on the Y-axis.

**Comment by baieric** [comment]
> Cola also renders my graph the best, however we recently had to switch to d3-force for this issue alone.

Wow, your Stack Overflow question is very illuminating! Thank you for sharing. It sounds like our use cases are similar. I'm a bit confused by d3-force because all my nodes overlap. Would you mind sharing your config?

**Comment by janhartmann** [comment]
Currently we are running with this configuration for d3-force:

```{
  name: "d3-force",
  animate: true,
  linkId: (data) => data.id,
  linkDistance: (link) => {
    const length = link.edgeLength;
    if (length && length > 1) {
      return weight;
    }
    return 85;
  },
  linkStrength: () => 0.3,
  xStrength: 0,
  yStrength: 0.15,
  yY: 0.5,
  velocityDecay: 0.6,
  collideRadius: 3,
  collideStrength: 1,
  manyBodyStrength: (_link, index) => {
    return index === 0 ? -2000 : -1000;
  }
}```

**Comment by maxkfranz** [comment]
Tim would be able to answer better about how Cola handles aspect ratios, but generally force-directed layouts try to optimise for the general forces and the graph topology.  That usually results in a more square result for most highly-connected graph, in order to get to an equilibrium state.

The FCOSE layout is of note in that it packs disconnected components well based on the viewport aspect ratio, e.g.:

<img width="1392" alt="Screen Shot 2020-10-01 at 11 13 51" src="https://user-images.githubusercontent.com/989043/94828602-a1108b00-03d7-11eb-80d4-e222fbfa0354.png">

**Comment by maxkfranz** [comment]
Aside: The d3-force layout is [packaged as a Cytoscape extension](https://github.com/shichuanpo/cytoscape.js-d3-force).  So if you want to add new features to that extension, you could make a pull request to that author's repo.  I'm not sure if that's the package that @janhartmann is using, or whether he's created a custom wrapper.

**Comment by baieric** [comment]
Thank you both for the recommendations! At first I had trouble getting either layout to behave as I wanted, but then I realized I had some problems with my implementation that just happened to not raise issues with the cola layout. A lot of tweaking later and the d3-force layout seems perfect for my use case. Thank you so much!
